name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:

# مهم: اجازه‌ی نوشتن برای این ورک‌فلو
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake svgs
        uses: Platane/snk@v3.2.0
        id: snake-svg
        with:
          github_user_name: sinaf2000
          outputs: |
            src/github-contribution-grid-snake.svg?palette=github-light
            src/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#3c7dd9
            src/github-contribution-grid-snake-default.svg?color_snake=#3c7dd9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      - run: git status

      - name: Push SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: src
        env:                               # ⚠️ توکن را دقیقاً روی همین استپ ست کن
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
