
name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */12 * * *"


  workflow_dispatch:
  push:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake
      - uses: Platane/snk@v3.2.0
        id: snake-svg
        with:
          github_user_name: sinaf2000
          
          outputs: |
            src/github-contribution-grid-snake.svg?palette=github-light
            src/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#3c7dd9
            src/github-contribution-grid-snake-default.svg?color_snake=#3c7dd9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

     
      - run: git status

      
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: src
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
